# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    session:
        enabled: true
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native



    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: ['en']

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file